/**
 * Giscus comments configuration (issue #43 — Disqus replacement).
 *
 * Giscus (https://giscus.app) backs post comments with GitHub Discussions.
 * It needs the opaque `repo-id` / `category-id` values that giscus.app
 * generates once GitHub Discussions is enabled on the repo and a suitable
 * (Announcements-type) category exists. Those ids are deployment secrets of
 * the non-sensitive kind: they arrive as `NEXT_PUBLIC_GISCUS_REPO_ID` /
 * `NEXT_PUBLIC_GISCUS_CATEGORY_ID` and gate whether the comments widget
 * renders at all — until both are set, `resolveGiscusConfig` returns null
 * and post pages simply show no comment section instead of a broken embed.
 *
 * The repo and category *names* have sane defaults (`TeahouseHQ/yian.dev`,
 * `Comments`) and can be overridden via `NEXT_PUBLIC_GISCUS_REPO` /
 * `NEXT_PUBLIC_GISCUS_CATEGORY`.
 *
 * Threads are mapped with Giscus's `specific` mapping onto the post's
 * stable front-matter `id` (a UUID), so renaming a post or editing its slug
 * never orphans the discussion.
 *
 * Every helper here is pure — no `process.env`, `document`, or `window`
 * access — so the whole contract stays unit-testable in the node vitest
 * environment; the only side effects live in the CommentsBox client
 * component. Callers must read each `NEXT_PUBLIC_*` variable as a static
 * `process.env.X` member expression (as CommentsBox does) so Next.js
 * inlines the values into the client bundle.
 */

import type { ReaderTheme } from "./theme";

/** Giscus app origin: client script source and postMessage target. */
export const GISCUS_ORIGIN = "https://giscus.app";

/**
 * Theme names accepted by Giscus that match our reader themes (ADR-0005):
 * the vocabularies are deliberately identical, so this aliases the reader
 * theme union rather than redefining it.
 */
export type GiscusTheme = ReaderTheme;

export type GiscusConfig = {
  /** `owner/name` of the repository hosting the Discussions. */
  repo: string;
  /** Opaque repository id generated by giscus.app. */
  repoId: string;
  /** Discussion category name threads are created in. */
  category: string;
  /** Opaque category id generated by giscus.app. */
  categoryId: string;
};

/** Raw, possibly-unset inputs read from the environment. */
export type GiscusEnv = {
  repo?: string;
  repoId?: string;
  category?: string;
  categoryId?: string;
};

const DEFAULT_REPO = "TeahouseHQ/yian.dev";
const DEFAULT_CATEGORY = "Comments";

/**
 * Resolve the environment into a {@link GiscusConfig}, applying the repo and
 * category name defaults. Returns null when either opaque id is unset or
 * empty — the "Giscus not configured yet" state — which callers must treat
 * as "render no comment section" rather than "render a broken widget".
 */
export function resolveGiscusConfig(env: GiscusEnv): GiscusConfig | null {
  if (!env.repoId || !env.categoryId) {
    return null;
  }
  return {
    repo: env.repo || DEFAULT_REPO,
    repoId: env.repoId,
    category: env.category || DEFAULT_CATEGORY,
    categoryId: env.categoryId,
  };
}

/**
 * The complete attribute map for the Giscus client `<script>` element,
 * including `src`. Keys are attribute names exactly as Giscus documents
 * them; callers apply every entry verbatim. The mapping is pinned to
 * `specific` with `term` (the post's stable id), reactions are on, metadata
 * emission is off (we consume no Giscus events), and the widget loads lazy
 * below the fold.
 */
export function buildGiscusScriptAttributes(
  config: GiscusConfig,
  term: string,
  theme: GiscusTheme
): Record<string, string> {
  return {
    src: `${GISCUS_ORIGIN}/client.js`,
    "data-repo": config.repo,
    "data-repo-id": config.repoId,
    "data-category": config.category,
    "data-category-id": config.categoryId,
    "data-mapping": "specific",
    "data-term": term,
    "data-reactions-enabled": "1",
    "data-emit-metadata": "0",
    "data-theme": theme,
    "data-lang": "en",
    "data-loading": "lazy",
    crossorigin: "anonymous",
  };
}

/**
 * The message payload asking Giscus to switch theme live (ADR-0005). Per
 * Giscus's postMessage protocol the request must be wrapped in an outer
 * `giscus` key — messages without it are silently ignored by the client —
 * and is delivered via `iframe.contentWindow.postMessage(message,
 * GISCUS_ORIGIN)`.
 */
export function giscusSetConfigMessage(theme: GiscusTheme): {
  giscus: { setConfig: { theme: GiscusTheme } };
} {
  return { giscus: { setConfig: { theme } } };
}
